# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: oozsertt <oozsertt@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/04/15 09:29:45 by oozsertt          #+#    #+#              #
#    Updated: 2022/04/15 09:37:51 by oozsertt         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = megaphone

SRCS = Megaphone.cpp

$(NAME) : all

all :
	c++ -Wall -Wextra -Werror -std=c++98 $(SRCS) -o $(NAME)

clean :

fclean :

re : fclean all